language: rust

rust:
  - 1.1.0
  - 1.2.0
  - nightly

script:
  - cargo build
  - cargo test
  - cargo doc --no-deps

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./.travis/update_docs.sh